### ISSUE TITLE
suggestion for more resolvers.

### ISSUE THREAD

**Issue by MPaandeey** [BonJarber/fresh-resolvers#1]
Get more nameservers at ```https://public-dns.info/nameservers.txt```  you will get more results better than previous.

**Comment by its0x08** [comment]
You can close this issue. It is alredy included [here](https://github.com/BonJarber/fresh-resolvers/blob/c5621c3915f9156fb2203e827772e471e97cf0bd/.github/workflows/refresh-resolvers.yaml#L35)
